package processing.computation.implementation.payload;

import common.interfaces.IPayloadElement;
import common.interfaces.IResource;
import org.cyberborean.rdfbeans.annotations.RDFBean;
import utils.implementation.FLuIDVocabulary;

;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: SnippetElement <br>
 * @version generated on Fri Jul 14 09:00:06 CEST 2017 by Blume Till
 */
@RDFBean(FLuIDVocabulary.CLASS_SNIPPET_ELEMENT)
public class SnippetElement implements IPayloadElement {


    @Override
    public void merge(IPayloadElement payloadElement) {

    }

    @Override
    public IResource getLocator() {
        return null;
    }
}
